### 3.3.2 다차원 배열의 계산

In [7]:
import numpy as np
A = np.array([1,2,3,4])
print(A)
print(np.ndim(A))
print(A.shape)
print(A.shape[0])

[1 2 3 4]
1
(4,)
4


In [8]:
b = np.array([[1,2],[3,4],[5,6]])
print(b)
print(np.ndim(b))
print(b.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [9]:
A = np.array([[1,2],[3,4]])
print(A.shape)
B = np.array([[5,6],[7,8]])
print(B.shape)
print(np.dot(A,B))

(2, 2)
(2, 2)
[[19 22]
 [43 50]]


### 3.3.3 신경망의 내적

In [10]:
X = np.array([1,2])
print(X.shape)
W = np.array([[1,3,5],[2,4,6]])
print(W)
print(W.shape)
Y = np.dot(X,W)
print(Y)

(2,)
[[1 3 5]
 [2 4 6]]
(2, 3)
[ 5 11 17]


In [15]:
X = np.array([1.0,0.5])
W1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
print(f'{X}, {X.shape}')
print(f'{W1}, {W1.shape}')

A1 = np.dot(X,W1)
print(f'A1 is {A1}, {A1.shape}')

[1.  0.5], (2,)
[[0.1 0.3 0.5]
 [0.2 0.4 0.6]], (2, 3)
A1 is [0.2 0.5 0.8], (3,)


In [16]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
Z1 = sigmoid(A1)
print(A1)
print(Z1)

[0.2 0.5 0.8]
[0.549834   0.62245933 0.68997448]


In [19]:
W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])
print(f'{Z1},{Z1.shape}')
print(f'{B2},{B2.shape}')
A2 = np.dot(Z1,W2)
Z2 = sigmoid(A2)
print(f'{A2},{A2.shape}')
print(f'{Z2},{Z2.shape}')

[0.549834   0.62245933 0.68997448],(3,)
[0.1 0.2],(2,)
[0.38646761 0.94514795],(2,)
[0.59543206 0.72013835],(2,)
